//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 资产管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPutInfo
    {
        public int AssetPutID { get; set; }
        public int AssetId { get; set; }
        public int AssetPutNum { get; set; }
        public int EmpolyId { get; set; }
        public System.DateTime AssetPutDate { get; set; }
        public string AssetPutReMark { get; set; }
    }
}
