//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 资产管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetInfo()
        {
            this.AssetDetailInfo = new HashSet<AssetDetailInfo>();
        }
    
        public int AssetId { get; set; }
        public int AssetTypeID { get; set; }
        public string AssetName { get; set; }
        public string AssetModel { get; set; }
        public string AssetCompany { get; set; }
        public string AssetReMark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetDetailInfo> AssetDetailInfo { get; set; }
    }
}
