//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 资产管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageRecordInfo
    {
        public int DamageRecordId { get; set; }
        public int AssetDetailId { get; set; }
        public int EmpolyId { get; set; }
        public System.DateTime DamageDate { get; set; }
        public string DamageCauses { get; set; }
        public string ProblemDescription { get; set; }
        public byte[] ProblemImange { get; set; }
        public int RecordState { get; set; }
        public string Repairman { get; set; }
        public Nullable<System.DateTime> RepairDates { get; set; }
        public string DamageRecordReMark { get; set; }
    
        public virtual EmpolyInfo EmpolyInfo { get; set; }
    }
}
