//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 资产管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeptInfo()
        {
            this.EmpolyInfo = new HashSet<EmpolyInfo>();
        }
    
        public int DeptId { get; set; }
        public Nullable<int> CampusId { get; set; }
        public string DeptName { get; set; }
        public string DeptReMark { get; set; }
    
        public virtual CampusInfo CampusInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpolyInfo> EmpolyInfo { get; set; }
    }
}
